name: What You Really Think
favicon: null
layout_spectrum: 0.49669
typography_spectrum: 0.65093
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#9f9f9f'
    - '#0c0c0c'
    - '#3a3a3a'
    - '#606060'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
