name: What You Really Think
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65093
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#9f9f9f'
    - '#0c0c0c'
    - '#3a3a3a'
    - '#606060'
  brandStrength: 0.5
  lightness: 0.4268973437137902
  saturation: 0.790356773417443
  rhythmicContrast: 0.5
purpose: []
