name: What You Really Think
favicon: null
layout_spectrum: 0.5270911832340062
typography_spectrum: 0.6629684390500188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.48571720672771335
  lightness: 0.4268973437137902
  saturation: 0.790356773417443
  rhythmicContrast: 0.07928793621249497
purpose: []
